### ISSUE TITLE
How build kdnet_delta.bin ?

### ISSUE THREAD

**Issue by Gelip** [MovAX0xDEAD/KDNET#1]
My guess is that you need to use the xdelta3.exe tool, but in what way?

**Comment by MovAX0xDEAD** [comment]
I don't understand, you aready have kdnet_delta.bin made by me.
To make own deltas:
xdelta3.exe -e -0 -f -vv -s orig_file.dll patched_file.dll  file_delta.bin

**Comment by Gelip** [comment]
OK, understand. The file can be done in two ways:
1. Your kdnet_delta.bin and original kdnet.dll
2, Using the original kdnet.dll file and _merge.cmd script
Build files have an identical control sum.
I did it with the version of the kdnet.dll 64-bit but when debugging is an error.
